export const FIREBASE_STORAGE_CONFIG = Symbol('FIREBASE_STORAGE_CONFIG');
export const FIREBASE_MEDIA_APP = Symbol('FIREBASE_MEDIA_APP');
export const FIREBASE_STORAGE_BUCKET = Symbol('FIREBASE_STORAGE_BUCKET');
